### ISSUE TITLE
Closed ticket inaccessible with vip plugin activated

### ISSUE THREAD

**Issue by Shaalia92** [pluginsGLPI/vip#2]
Hello,

When the VIP plugin is active, the ticket menu of all closed ticket is not accessible anymore.

GLPI 10.0.3
VIP 1.8.1

VIP disabled :
![image](https://user-images.githubusercontent.com/116336742/197130343-cddd8f30-ecb4-401f-8caa-1822a8e627cc.png)

VIP enabled :
![image](https://user-images.githubusercontent.com/116336742/197130385-b3dac088-8ee2-442d-bea5-26fbef4e9e4a.png)

At disposal if you need more info

Have a good day

**Comment by altadeos** [comment]
Hello,

I have the same issue since the upgrade of GLPI.

Could you please solve it ? 

Have a good day.

**Comment by tsmr** [comment]
Corrected in last release

https://github.com/pluginsGLPI/vip/releases/tag/1.8.2

**Comment by Shaalia92** [comment]
Thanks for the fast fix. It works 👌

Have a nice day !

**Comment by altadeos** [comment]
Thank you for the fix.

Best regards
